### ISSUE TITLE
Organize structure 📚

### ISSUE THREAD

**Issue by itstyonirwansyah** [DashCruft-Nation/DisCruft-Bot#111]
Organize the structure of the code, try putting your codebase inside the `src` folder.

- [ ]  Organize font files ( .otf , .ttf)
- [ ]  Put database models inside one folder ( try renaming the other one outside source)

**Comment by birbified** [comment]
this project is kinda dead 😩

**Comment by Assassin-1234** [comment]
imma close this issue since the whole project is dead, will try and revive back by contributing tho! thanks for the enhancement suggestions, will implement these in the next pr / commits I do :)
