### ISSUE TITLE
new issue 

### ISSUE THREAD

**Issue by Vinayak119A** [DashCruft-Nation/DisCruft-Bot#116]
Hey, I am Vinayak Kanjker I would like to contribute in this app can you please assign me a task .
This is for my open source contribution class.
please contact me at vinukanjiker@gmail.com

**Comment by Assassin-1234** [comment]
I'm sorry to inform you but the project is unmaintained as of now and I dont think that will change for the foreseeable future. If you wish, you can contribute to [lazap](https://github.com/Lazap-Development/lazap) game launcher that is maintained by the same team
