### ISSUE TITLE
coinflip command

### ISSUE THREAD

**Issue by GeneralHubertGaleforce** [DashCruft-Nation/DisCruft-Bot#44]
when i do the coin flip commands it sends me the same thing twice. 
![error](https://user-images.githubusercontent.com/73068166/112182714-33b31980-8c06-11eb-99c5-f388bede3ab0.png)

**Comment by Assassin-1234** [comment]
hey there! you are most probably running 2 instances of the bot, I checked the code and its supposed to send only 1 embed.

**Comment by GeneralHubertGaleforce** [comment]
Well for me it sends two. Same with the turtle command.

**Comment by Assassin-1234** [comment]
click the trash icon in visual studio code to close a terminal, you have 2 of them running at the same time 
![image](https://user-images.githubusercontent.com/68866924/112184390-2ce7cf00-8c25-11eb-8b34-4204f2d7a86f.png)

**Comment by GeneralHubertGaleforce** [comment]
Ah it worked. thank you
