### ISSUE TITLE
pp command no work

### ISSUE THREAD

**Issue by Rachniotov** [DashCruft-Nation/DisCruft-Bot#72]
It just says undefined to everything and pp very smol
![Screenshot_20210324_192741](https://user-images.githubusercontent.com/71971848/112322716-26199480-8cd7-11eb-9f67-0c7d923de3ec.jpg)

**Comment by LegItMate** [comment]
Naman should check

**Comment by LegItMate** [comment]
If he isnt gonna ill check

**Comment by DashCruft** [comment]
Thank you so much for noticing this problem!

Its now has been fixed :)
