### ISSUE TITLE
Cat command problom

### ISSUE THREAD

**Issue by GeneralHubertGaleforce** [DashCruft-Nation/DisCruft-Bot#83]
When i do the command it doesn't show a pic. It shows "cat.png" But not image
![cat](https://user-images.githubusercontent.com/73068166/112690004-1ee7b780-8e8c-11eb-8d94-580dff6a4817.png)

**Comment by Assassin-1234** [comment]
hey there! thanks for reporting, I'll take a look at the command and try to fix it, will give you updates regarding this

**Comment by DashCruft** [comment]
Thank you for reporting this bug.

We'll investigate the problem and update you asap!

**Comment by Assassin-1234** [comment]
this has been fixed! we've deleted the cat command

**Comment by GeneralHubertGaleforce** [comment]
lol
